openapi: 3.1.0
info:
  title: HerramientaLectorDoc
  version: 1.0.0
servers:
  - url: https://script.google.com/macros/s/AKfycbyZq2JM4NohCcy2rf3GQObf-irmU-Aj_OBh5ohhSYDzKRbzAEStprVhd1w-oNbbVICxFw/exec
paths:
  /exec:
    get:
      operationId: leerDocumento
      summary: Lee un documento de Google.
